### ISSUE TITLE
use a callable for default value ?

### ISSUE THREAD

**Issue by lunika** [chanmix51/ParameterJuicer#1]
Almost everywhere it is possible to use a callable to clean, validate, etc but not for the default value.

I think it can be a good think to use a callable here to because a default value can take some resources like computing a `uuid`. Using a callable we will have a "lazy loaded" default value.

What do you think ?

**Comment by chanmix51** [comment]
Done in e8abb2922a4a023aa6426111a1e70e26fb85e491 (see #4)
