### ISSUE TITLE
add field name in the cleaner and validator callable

### ISSUE THREAD

**Issue by lunika** [chanmix51/ParameterJuicer#3]
Having the name of the field validated can help to construct a nicer error message.

This is maybe the behaviour you wanted in the fixtures you implemented https://github.com/chanmix51/ParameterJuicer/blob/master/sources/tests/Fixtures/PikaChuJuicer.php#L44 `$name` field does not exists.

**Comment by chanmix51** [comment]
I had a hard time removing the field name from validators :) It may remains some glitches here and here but the field names are now stored in the exception. When `Validation::getExceptions()` is called it returns an associative array with the field name as key and an array of the associated exceptions as value.

This makes the error messages simple to write without caring about global formatting.

**Comment by lunika** [comment]
Hmm right with the fancyMessage method we have all the needed informations.
