### ISSUE TITLE
Compare two fields

### ISSUE THREAD

**Issue by rgazelot** [chanmix51/ParameterJuicer#8]
I didn't find a way to compare two fields. For example if you have an array with a `min` and `max` value, it could be useful to check that `max` is greater than `min` in its validation.

Did you already though about that case and have any idea?

**Comment by chanmix51** [comment]
Yes, its place is in the squash method, I am going to update the documentation showing how to do that. There are no way to do this using callables btw, that is a feature that could take place in a new version.

**Comment by chanmix51** [comment]
It is actually possible to perform that with the 1.0 version:

``` php
<?php
$juicer = (new Juicer)
    ->addField('my_form')
        ->addJuicer('my_form', (new PasswordFormJuicer)
        ->addValidator('my_form', function($val) {
            if ($val['pass'] !== $val['repass']) {
                throw new ValidationException('passwords are different');
            }
        });
```
It may not be ideal but it works.

**Comment by lunika** [comment]
if both values are at the root of the array this will not work.

How to implement your example with this array ? `['min' => 3, 'max' => 5]`

An idea could be to inject the whole array as second argument to the validator callable ?

**Comment by chanmix51** [comment]
It is the case when you embed juicers:

```php
$juicer = (new Juicer)
    ->addField('my_form')
        ->addJuicer('my_form', (new Juicer)
            ->addField('min')
            ->addField('max'))
        ->addValidator('my_form', function($val) {
            if ($val['min'] > $val['max']) {
                return 'min > max'; }
        });
try {
    $values = $juicer->squash(['my_form' => ['min' => 3, 'max' => 5]]);
} catch (…) {
```

**Comment by chanmix51** [comment]
Overriding the `squash` method has advantages in the case of custom juicers:

```php
class MyJuicer extends ParameterJuicer
{
    public function squash(array $values)
    {
        try {
            $values = parent::squash($values);
            // computations made from here can assume all fields exist
            // and are valid.
            if ($values['pass'] !== $values['repass']) {
                throw new ValidationException('passwords do not match');
            }
        } catch (ValidationException $e) {
            // do extra computations if validation fails.
            throw $e;
        }

        return $values;
    }
}
```

**Comment by chanmix51** [comment]
imho, the nicest way to do it would be something like: When no fields are specified using the `addValidator` method a global validator is set. The callable is called with the array of the form’s values. 

The min max problem would then be solved like this:
```php
$juicer = (new Juicer)
        ->addField('min')
        ->addField('max'))
        ->addValidator(function(array $val) {
            if ($val['min'] > $val['max']) {
                return 'min > max'; }
        });
try {
    $values = $juicer->squash(['min' => 3, 'max' => 5]);
} catch (…) {
```
From this example, a new problem emerges: if one or both of the two fields are not set, of course a validation exception will be prepared but the global callable will raise a warning because at least a field does not exist. If fields are required then they must be created with no value.

This being said, the proposed implementation of the `addValidator` method implies switching the argument list so the `field` parameter would be optional. This is not BC.

**Comment by rgazelot** [comment]
I don't like the first proposition https://github.com/chanmix51/ParameterJuicer/issues/8#issuecomment-307787209. Even if it works, I really don't want to "simulate" a new level to do the job.

https://github.com/chanmix51/ParameterJuicer/issues/8#issuecomment-309135595 I love this way to validate globally the entire data set. I understand the BC issue by switching arguments. Your entire validator system is based on fields and making `$field` optional in `addValidator` will lead you to a lot of changes everywhere. 

What about adding a `addGlobalValidator` method that will be called after `clean` and `validate` in the `squash` process? The entire data set could be injected into these callbacks and could be used to validate the data set globally as you proposed.

Nevertheless, the issue of optional fields is not solved 🤔

**Comment by chanmix51** [comment]
`ParameterJuicer::addGlobalValidator()` sounds ok to get round the BC problem. 

Regarding the missing required fields (or optional fields) imho, the good way would be: when a missing mandatory field is found.
 1.  load the `ValidationException` with the according error message.
 1.  create the missing mandatory fields with no value (NULL) so the key exists at the end of the validation process hence global validators can use those keys. Optional fields are still optional so global validators would have to test for their existence in all cases.

The last bit of real life use case would be to decide the global validation trigger upon fields validation failure. A default global validation policy would be to trigger global validation whatever fields validation succeeds or not. An alternate policy would be not to launch global validation if fields validation fails.

**Comment by chanmix51** [comment]
A solution made without BC break is the adding of the form cleaners & validators ( see 2db2453 ) 

```php
$juicer = (new Juicer)
        ->addField('min')
        ->addField('max'))
        ->addFormValidator(function(array $val) {
            if ($val['min'] >= $val['max']) {
                return 'min is equal or greater than max'; }
        });
try {
    $values = $juicer->squash(['min' => 3, 'max' => 5]);
} catch (…) {
```

**Comment by rgazelot** [comment]
Sounds really good. Could you tag and release this work please to use it?

**Comment by chanmix51** [comment]
Before I tag it, could you please test the form validators & default values to see if it meets your requirements?

**Comment by lunika** [comment]
I just test it, I need it too.

First thing, I expect in the array to retrieve all the  mandatory fields declared in my juicer, otherwise I will have to use some `isset` or `array_key_exists`, this is I think the `addField` work.

Second, the behaviour of this function is different than other validator, if my callable return null there is no error. Why not throwing a `ValidationException` like in a specific validator ?

**Comment by lunika** [comment]
a workaround could be to use a default value, but I'm not fan of this solution.

**Comment by chanmix51** [comment]
There are several points in your post, I will answer them one by one.

1. The fields are not created by the cleaner system even though they are mandatory. Furthermore, they can be unset by the cleaners using the `RemoveFieldException`. I do not think we can avoid testing fields existence in form cleaners unless using a special type for fields (like a Maybe monad). I think the use of form validators and cleaners is not that frequent so maybe we can afford a non easy developer interface in benefit of speed.
2. Fields validators and form validators work the same way. If they return a string or throw a `ValidationException` this makes the validation to fail. The case of validators using a string return value as `ValidationException` has been added in 7216872 this makes validators more concise and readable imho.

**Comment by chanmix51** [comment]
The code above could be written like

```php
$juicer = (new Juicer)
        ->addField('min')
        ->addField('max'))
        ->addFormValidator(function(array $val) {
            if ($val['min'] >= $val['max']) {
                throw new ValidationException('min is equal or greater than max'); }
        });
try {
    $values = $juicer->squash(['min' => 3, 'max' => 5]);
} catch (…) {
```

**Comment by chanmix51** [comment]
I am thinking while I am typing: maybe there could be 2 strategies for the global validation:
1. `conditional`: fields validation must be OK to trigger form validation
1. `always`: form validation is always triggered

Default would be `conditional` so mandatory fields would be presents when validating the form.
Edit: see [this branch](https://github.com/chanmix51/ParameterJuicer/blob/06a60cc2e53a578220897bcd185d1d49ac17febd/sources/tests/Unit/ParameterJuicer.php#L578) for this test case.
